# Generated by Django 4.1.7 on 2023-03-30 00:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AppPesca', '0003_mensaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesca',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
