# Generated by Django 4.1.7 on 2023-03-30 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppPesca', '0004_pesca_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pesca',
            old_name='created_at',
            new_name='creado_el',
        ),
    ]
