# Generated by Django 4.1.7 on 2023-03-30 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPesca', '0005_rename_created_at_pesca_creado_el'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesca',
            name='creado_el',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
